import { UserProfile } from './users';

export const mockUsers: UserProfile[] = [
  {
    id: '1',
    email: 'sophia.g@example.com',
    name: 'Sophia',
    age: 24,
    location: 'New York, NY',
    role: 'Sugar Baby',
    sex: 'Female',
    bio: 'Art student who loves exploring museums and trying new cuisines. Looking for a mentor to guide and support my journey.',
    interests: ['Art', 'Fine Dining', 'Photography', 'Museums'],
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: '2',
    email: 'james.b@example.com',
    name: 'James',
    age: 45,
    location: 'San Francisco, CA',
    role: 'Sugar Daddy',
    sex: 'Male',
    bio: 'Successful tech entrepreneur who enjoys mentoring ambitious individuals. I appreciate fine wine, international travel, and stimulating conversation.',
    interests: ['Travel', 'Wine Tasting', 'Mentorship', 'Tech'],
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: '3',
    email: 'chloe.m@example.com',
    name: 'Chloe',
    age: 22,
    location: 'Miami, FL',
    role: 'Sugar Baby',
    sex: 'Female',
    bio: 'Fitness model and aspiring influencer. I love the beach, yachting, and living a life of luxury. Seeking a partner who can keep up with my vibrant lifestyle.',
    interests: ['Fitness', 'Social Media', 'Yachting', 'Luxury'],
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: '4',
    email: 'william.t@example.com',
    name: 'William',
    age: 52,
    location: 'London, UK',
    role: 'Sugar Daddy',
    sex: 'Male',
    bio: 'A distinguished gentleman with a passion for the finer things in life. I enjoy opera, collecting art, and spontaneous weekend getaways.',
    interests: ['Art Collecting', 'Opera', 'Travel', 'Fine Dining'],
    image: 'https://placehold.co/400x400.png',
  },
    {
    id: '5',
    name: 'Isabella',
    age: 26,
    email: 'isabella.r@example.com',
    location: 'Paris, France',
    role: 'Sugar Baby',
    sex: 'Female',
    bio: 'Fashion design student with a love for haute couture and romantic evenings. Seeking a sophisticated partner to share beautiful experiences with.',
    interests: ['Fashion', 'Travel', 'Art', 'Cuisine'],
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: '6',
    name: 'Alex',
    age: 38,
    email: 'alex.doe@example.com',
    location: 'Austin, TX',
    role: 'Sugar Daddy',
    sex: 'Male',
    bio: 'Music producer and entrepreneur. I enjoy live concerts, discovering new artists, and helping talented people achieve their dreams.',
    interests: ['Music', 'Concerts', 'Startups', 'Mentoring'],
    image: 'https://placehold.co/400x400.png',
  },
];
