
import { UserProfile } from './users';

export const mockUsers: UserProfile[] = [
  {
    id: '1',
    email: 'alex.doe@example.com',
    name: 'Alex Doe',
    age: 28,
    location: 'New York, NY',
    role: 'Sugar Daddy',
    sex: 'Male',
    bio: 'Generous and successful entrepreneur looking for a smart and ambitious companion to share life\'s luxuries. I enjoy fine dining, traveling, and mentoring.',
    interests: ['Fine Dining', 'Travel', 'Mentorship', 'Art'],
    image: 'https://placehold.co/600x600.png',
  },
  {
    id: '2',
    email: 'jessica.smith@example.com',
    name: 'Jessica Smith',
    age: 22,
    location: 'Los Angeles, CA',
    role: 'Sugar Baby',
    sex: 'Female',
    bio: 'Ambitious university student with a passion for fashion and culture. Seeking a mature and supportive partner to explore the world with.',
    interests: ['Fashion', 'Culture', 'Photography', 'Yoga'],
    image: 'https://placehold.co/600x600.png',
  },
    {
    id: '3',
    email: 'samantha.jones@example.com',
    name: 'Samantha Jones',
    age: 45,
    location: 'Miami, FL',
    role: 'Sugar Mommy',
    sex: 'Female',
    bio: 'Established and independent woman who enjoys the finer things in life. Looking for a charismatic and driven young man to spoil and accompany me on adventures.',
    interests: ['Sailing', 'Wine Tasting', 'Theater', 'Charity Galas'],
    image: 'https://placehold.co/600x600.png',
  },
  {
    id: '4',
    email: 'chris.wilson@example.com',
    name: 'Chris Wilson',
    age: 25,
    location: 'Chicago, IL',
    role: 'Sugar Baby',
    sex: 'Male',
    bio: 'Young professional with big dreams. I\'m looking for a mentor and partner who can guide me and enjoy my vibrant energy and zest for life.',
    interests: ['Startups', 'Fitness', 'Live Music', 'Cooking'],
    image: 'https://placehold.co/600x600.png',
  },
  {
    id: '5',
    email: 'emily.white@example.com',
    name: 'Emily White',
    age: 24,
    location: 'San Francisco, CA',
    role: 'Sugar Baby',
    sex: 'Female',
    bio: 'Creative soul and artist. I appreciate beauty in all its forms and seek a sophisticated partner to share meaningful experiences with.',
    interests: ['Painting', 'Museums', 'Poetry', 'Hiking'],
    image: 'https://placehold.co/600x600.png',
  },
  {
    id: '6',
    email: 'david.green@example.com',
    name: 'David Green',
    age: 52,
    location: 'Boston, MA',
    role: 'Sugar Daddy',
    sex: 'Male',
    bio: 'Well-read and well-traveled academic. I offer stability, wisdom, and a generous heart. Looking for an intelligent and curious young woman.',
    interests: ['Literature', 'History', 'Classical Music', 'Sailing'],
    image: 'https://placehold.co/600x600.png',
  },
];
